<div class="site-logo">
	<h1>
		<a id="link-site" name="link-site" href="http://lintinzone.com/" target="_blank">
			<img width="477" height="83" id="site-logo" src="../public/images/lintinzone-logo.png" alt="LintinZone - Social Shipping Network" title="LintinZone - Social Shipping Network" />
		</a>
	</h1>
	<h2>
		<a href="http://lintinzone.com/" target="_blank">
			<img width="477" height="50" src="../public/images/lintinzone-slogan.png" alt="LintinZone - Social Shipping Network" title="LintinZone - Social Shipping Network" />
		</a>
	</h2>
</div>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19916808-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4e51d7a21c1d61be"></script>
