<span id="copyright">Bản quyền thuộc về LintinZone &copy; 2011-<?php echo date('Y'); ?>.</span>
<a href="http://www.facebook.com/LintinZone" target="_blank" title="LintinZone on Facebook">
	<img width="32" height="32" src="public/images/facebook-32.png" alt="LintinZone on Facebook" />
</a>
<a href="http://twitter.com/@LintinZone" target="_blank" title="LintinZone on Twitter">
	<img width="32" height="32" src="public/images/twitter-32.png" alt="LintinZone on Twitter" />
</a>
<a href="https://plus.google.com/b/114591945709472470617/" target="_blank" title="LintinZone on Google+">
	<img width="32" height="32" src="public/images/googleplus-32.png" alt="LintinZone on Google+" />
</a>
<a href="?lang=vi">
	<img width="24" height="24" src="public/images/vi_active.gif" alt="Tiếng Việt Nam" title="Bạn đang xem trang này bằng tiếng Việt Nam." />
</a>
<a href="?lang=en">
	<img width="24" height="24" src="public/images/en_inactive.gif" alt="English" title="English" />
</a>
